### ISSUE TITLE
弟子规 ：而亲人

### ISSUE THREAD

**Issue by shanuan** [shanuan/blog#17]

**Comment by littleflute** [comment]
![img_20170926_160402](https://user-images.githubusercontent.com/17950965/30888296-a50aa63a-a2d4-11e7-8363-bf968df96586.jpg)

**Comment by littleflute** [comment]
![img_20170926_155451](https://user-images.githubusercontent.com/17950965/30888394-38b87a7e-a2d5-11e7-940a-e05360920346.jpg)

**Comment by littleflute** [comment]
![img_20170926_160440](https://user-images.githubusercontent.com/17950965/30888462-87807792-a2d5-11e7-9bd1-b853066d18d4.jpg)
